Wdp190504 8
xkxd/WDP-1905-04 pull request #12
Opened 2019-05-27 19:25 UTC by DawMas

Wszystko działa zgodnie z poleceniem zadania. Mam jedynie wątpliwości czy może zostać takie rozwiązanie odnośnie usunięcia linka z 'READ MORE' : 
<div class="more"><div class="btn-main">Read more</div></div>  ?

2019-05-27 23:44 UTC, matwjablonski requested changes

2019-05-27 23:44 UTC, matwjablonski commented on src/sass/components/_button.scss
> +    //background-color: $primary;
nie zostawiaj zakomentowanego kodu

2019-05-27 23:44 UTC, matwjablonski commented on src/sass/components/_post-box.scss
> +      color: black;
kolory w hexach i do zmiennych

2019-05-27 23:44 UTC, matwjablonski commented on src/sass/components/_post-box.scss
> +      div {
zbyt duża specyficzność selektora wyjdzie - zmniejsz ją ;)

2019-05-27 23:44 UTC, matwjablonski commented on src/sass/components/_post-box.scss
> +.post-box:hover {
linia przerwy nad

2019-05-28 19:12 UTC, DawMas commented
Dzięki za uwagi. Poprawiłem ;)

2019-05-28 22:35 UTC, matwjablonski requested changes

2019-05-28 22:35 UTC, matwjablonski commented on src/sass/components/_post-box.scss
> +      .btn-main {
ten ruch jeszcze bardziej zwiększył specyficzność ;) ideą jest nie zwiększać niepotrzebnie specyficzności:

```
.more {
  text-align: center;
  padding-top: 30px;
}

.btn-main {
  display: inline-block;
}
```

2019-05-29 16:26 UTC, DawMas commented on src/sass/components/_post-box.scss
> +      .btn-main {
rozumiem, poprawione ;)

2019-06-03 16:55 UTC, MichalAW commented
Brak uwag z mojej strony

2019-06-05 18:48 UTC, matwjablonski commented
konflikty :(

2019-06-05 20:04 UTC, DawMas commented
> 
> 
> konflikty :(

Konflikty usunięte, proszę o merge ;)

2019-06-05 20:14 UTC, matwjablonski requested changes

2019-06-05 20:14 UTC, matwjablonski commented on src/partials/70_section-blog-posts.html
> +                alt="szafka duza"
dlaczego po polsku?

2019-06-05 20:21 UTC, DawMas commented on src/partials/70_section-blog-posts.html
> +                alt="szafka duza"
poprawione :)

2019-06-06 03:11 UTC, lukaszewczak commented
Nadal występują konflikty

2019-06-06 05:30 UTC, matwjablonski approved these changes

2019-06-06 13:37 UTC, xkxd commented
@DawMas , rozwiąż proszę konflikty :)

2019-06-06 19:00 UTC, DawMas commented
@xkxd konflikty rozwiązane ;)

2019-06-06 19:46 UTC, merged