Wdp190504 17
xkxd/WDP-1905-04 pull request #23
Opened 2019-06-03 19:01 UTC by MegDeri

Dodalam drugi element div z klasa row w _50_section-products, zeby odniesc sie do wyswietlanych boksow ze zdjeciami produktu. Wiem ze jak bedzie zaimplementowana karuzela to kod trzeba bedzie troche przerobic. Poki co karuzeli nie ma jeszcze w projekcie, takze  rozwiazanie tego zadania jest "tymczasowe".

PROBLEM: kod w projekcie nie dziala, klasy: active i show nie dodaja sie na elementachDOM. Nie wiem jak to rozwiazac ten sam fragment kodu sprawdzilam w Codepen-ie i wszystko dziala tam poprawnie. Link ponizej:
https://codepen.io/Magda_Aderibigbe/pen/JVbYap

2019-06-06 04:19 UTC, lukaszewczak requested changes

2019-06-06 04:19 UTC, lukaszewczak commented on src/partials/50_section-products.html
> +            <li><a href="#dining" class="accordion">Chair</a></li>
Twój selektor
`let lists = document.querySelectorAll('.accordion a');`
 którego użyłaś w js do pobrania elementów nie złapie tego elementu. Struktura html musiałby by wyglądac inaczej, np tak jak w Twoim przykładzie na codepen, gdzie klasę `accordion ` masz na elemencie `li`

2019-06-06 04:19 UTC, lukaszewczak commented on src/scripts/tab.js
> +console.log('test');
Usuwamy console.log

2019-06-06 04:19 UTC, lukaszewczak commented on src/scripts/tab.js
> +console.log('test');
Na początku pliku dobrze jest ustawić tryb ścisły po przez dyrektywę 'use strict';

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode

2019-06-06 04:19 UTC, lukaszewczak commented on src/scripts/tab.js
> +    this.item = item;
Ta konstrukcja jest tutaj nie potrzebna

2019-06-06 04:19 UTC, lukaszewczak commented on src/scripts/tab.js
> +    var self = this.item;
Ta konstrukcja jest tutaj nie potrzebna, masz dostęp do klikniętego elementu po przez parametr `item`

2019-06-06 04:19 UTC, lukaszewczak commented on src/scripts/tab.js
> +var tabContent = function () {
Jeżeli zaczęłaś używać `let` do deklaracji zmiennych to używaj `let` i ` const` zamiast `var` w całym kodzie

2019-06-06 21:08 UTC, MegDeri commented
Poprawione, kod dziala.  Narazie ze wzgledu na to ze nie ma jeszcze karuzeli boksy wyswietlaja sie w dwoch <row> co powoduje  ze jest pusta przestrzen pomiedzy sekcjami. Jak przyjdzie na to karuzela to wszystko bedzie w jednym rzedzie i bardziej estetycznie...

2019-06-07 03:19 UTC, lukaszewczak requested changes

2019-06-07 03:19 UTC, lukaszewczak commented on src/scripts/tab.js
> +    for (var i = 0; i < lists.length; i++) {
`let` zamiast `var`, jeżeli stosowany jest ES6 to spójnie przez cały kod, bez mieszania ze 'starym' `var`.

2019-06-07 03:19 UTC, lukaszewczak commented on src/scripts/tab.js
> +    // remove all show
Zbędny komentarz, widać co robi poniższy kod

2019-06-08 21:26 UTC, MegDeri commented
poprawione

2019-06-09 03:06 UTC, lukaszewczak approved these changes

2019-06-09 03:06 UTC, merged