Wdp190504-24
xkxd/WDP-1905-04 pull request #30
Opened 2019-06-08 11:51 UTC by DawMas

Na stronie należy dodać sekcję "Promocje" według designu:

https://uploads.kodilla.com/bootcamp/wdp/group-project-01/section-deals.png

Jest to zwykła statyczna sekcja (HTML i CSS). Wszystkie 3 boxy powinny być stałej wysokości - nawet, jeżeli użyje się większego zdjęcia w tle któregoś z nich, nie powinno ono wychodzić poza dany box, ani zmieniać jego rozmiaru.

Rozmiar boxów ze zdjęciami przypisane na stałe.

2019-06-08 20:53 UTC, lukaszewczak commented
@DawMas rozwiąż proszę konflikty

2019-06-08 21:40 UTC, DawMas commented
Rozwiązane :)

2019-06-09 03:01 UTC, lukaszewczak requested changes

2019-06-09 03:01 UTC, lukaszewczak commented on src/sass/components/_deals.scss
> +    color: #fff;
Kolor do zmiennej

2019-06-09 03:01 UTC, lukaszewczak commented on src/sass/components/_deals.scss
> +    border: 3px solid #fff;
Kolor do zmiennej

2019-06-09 19:38 UTC, DawMas commented on src/sass/components/_deals.scss
> +    border: 3px solid #fff;
poprawione ;)

2019-06-10 03:24 UTC, lukaszewczak requested changes

2019-06-10 03:24 UTC, lukaszewczak commented on src/partials/40_section-deals.html
> +              <img src=".\images\fotel2.jpg" alt="chairs" />
Źle zapisana ścieżka, zamiast forward-slash `/` został użyty backslash `\`, ta sma sytuacja jest w linii 38
Podana ścieżka musi być poprawnym URL-em lub jego fragmentem , do poczytania 
https://html.spec.whatwg.org/dev/embedded-content.html#attr-img-src
https://url.spec.whatwg.org/#valid-url-string

2019-06-10 05:56 UTC, matwjablonski commented
masz konflikty - proszę rozwiąż :)

2019-06-10 16:06 UTC, DawMas commented on src/partials/40_section-deals.html
> +              <img src=".\images\fotel2.jpg" alt="chairs" />
uwagi poprawione ;)

2019-06-10 16:06 UTC, DawMas commented
> 
> 
> masz konflikty - proszę rozwiąż :)

rozwiązane ;)

2019-06-10 16:27 UTC, MichalAW commented
Kod jest ok, można robić merge.

2019-06-10 17:23 UTC, lukaszewczak approved these changes

2019-06-10 17:23 UTC, merged