Add flickity files
xkxd/WDP-1905-04 pull request #37
Opened 2019-06-13 19:13 UTC by DawMas

Wpisy na blogu mają być karuzelą, analogicznie do sekcji "New furniture", tylko z innymi ustawieniami liczby wyświetlanych elementów (tzn. ma być analogicznie do tego jak zrobiono w tasku RWD)

Wyskakuje mi error przy robieniu commita związany ze zmiennymi karuzeli 'flkty' oraz 'flickity'

2019-06-13 21:31 UTC, matwjablonski commented
którego zadania dotyczy ten PR?

2019-06-14 04:46 UTC, DawMas commented
Początkowo pomyliłem numery zadań. Dzis naprowadze; )

2019-06-15 10:27 UTC, lukaszewczak commented
@DawMas którego zadania dotyczy ten PR?

2019-06-15 14:22 UTC, DawMas commented
Dotyczy zadania 26 ale na poczatku pomyliły mi się branche i robiłem zad 20, dlatego PR był zrobiony przez przypadek - zadanie nie jest jeszcze skończone ;)

2019-06-17 18:57 UTC, DawMas commented
Zadanie skończone, proszę o review i merge

2019-06-17 22:15 UTC, matwjablonski requested changes

2019-06-17 22:15 UTC, matwjablonski commented on src/sass/components/_gallery.scss
> +    border: 1px solid $grey-color;
właściwości dla box-left daj powyżej reguły img

2019-06-17 22:15 UTC, matwjablonski commented on src/sass/components/_gallery.scss
> +  .last-price {
linia przerwy pomiędzy regułami

2019-06-17 22:15 UTC, matwjablonski commented on src/sass/components/_gallery.scss
> +    width: 250px;
właściwości wyżej

2019-06-17 22:15 UTC, matwjablonski commented on src/sass/components/_gallery.scss
> +    a {
linia przerwy nad `a`

2019-06-18 15:33 UTC, DawMas commented
Poprawione ;)

2019-06-27 08:33 UTC, xkxd approved these changes

2019-06-27 08:33 UTC, merged