Task wdp190504-22+23
xkxd/WDP-1905-04 pull request #42
Opened 2019-06-17 07:58 UTC by Jakubcho

Opis problemu: Na szerokościach mobile należy ukryć lewy slider ("Hot deals") i pokazywać tylko prawy, na całą szerokość containera.
Na mobile i tabletach ma działać przesuwanie slajdów za pomocą swipe oraz klikania w nawigację slidera.
Opis rozwiązania:
Dodałem display:none na małych rozdzielczościach dla Hot deals, działa klikanie nawigacji slidera oraz odpowiednie przyciski, 

Opis problemu:
Slidery mają działać niezależnie od siebie, tzn. przesuwanie jednego nie powinno wpływać na drugi.
Slider po lewej powinien mieć autoplay (3 sekundy). Niezależnie od tego powinna działać nawigacja (kropki nad sliderem), by dało się przełączać slajdy ręcznie. 
W sliderze po prawej nie ma być autoplay, nawigacja w nim powinna być możliwa tylko przy pomocy strzałek.

Opis rozwiązania:
Dodałem 2 osobne karuzele dzięki czemu działają niezależnie, 
Slidery po lewej maja autoplay 3 sekundy dodatkowo nawigacja górna działa, 
Nie ma autoplay z prawej strony strzałki działają

Bardzo proszę o ewentualne opinie lub merge :)

2019-06-17 16:27 UTC, MichalAW commented
kod jest ok, możesz ewentualnie usunąć zera i zostawić same wartości po kropce jak np masz : http://prntscr.com/o2ztbv

to może być margin-left: .5rem;

ale to są szczegóły ;)

2019-06-18 11:11 UTC, lukaszewczak commented
@Jakubcho usuń proszę konflikty

2019-06-18 11:49 UTC, Jakubcho commented
@lukaszewczak konflikt rozwiązany,

2019-06-18 14:48 UTC, lukaszewczak requested changes

2019-06-18 14:48 UTC, lukaszewczak commented on README.md
> +
Zmiany na tym pliku są niepotrzebne

2019-06-18 16:45 UTC, xkxd approved these changes

2019-06-18 16:47 UTC, merged