Wdp190504 10
xkxd/WDP-1905-04 pull request #7
Opened 2019-05-27 17:12 UTC by MegDeri

2019-05-31 21:30 UTC, matwjablonski requested changes

2019-05-31 21:30 UTC, matwjablonski commented on src/sass/components/_header.scss
> +          .list-ul {
linia przerwy pomiędzy regułami

2019-05-31 21:30 UTC, matwjablonski commented on src/sass/components/_header.scss
> +                background-color: rgba(36, 34, 34, 0.4);
bez 0

2019-05-31 21:30 UTC, matwjablonski commented on src/sass/components/_header.scss
> +                color: #ffffff;
kolor do zmiennych

2019-05-31 21:30 UTC, matwjablonski commented on src/sass/components/_header.scss
> +                background-color: rgba(36, 34, 34, 0.4);
+ kolor do zmiennych

2019-05-31 21:30 UTC, matwjablonski commented on src/sass/components/_header.scss
> +            .link-sofa > ul > li > a {
zbyt dużo zagnieżdzeń - popraw specyficzność

2019-05-31 21:30 UTC, matwjablonski commented on src/sass/components/_header.scss
> +              color: rgb(46, 44, 44);
kolor do zmiennej

2019-05-31 21:30 UTC, matwjablonski commented on src/sass/components/_header.scss
> +            color: #b0b0b0;
kolor do zmiennej

2019-06-02 15:26 UTC, MegDeri commented
zad poprawione, prosze o review  lub merge.

2019-06-02 19:05 UTC, xkxd commented
@MegDeri, rozwiąż proszę konflikty

2019-06-03 17:50 UTC, MegDeri commented
konflikty rozwiazane

2019-06-04 18:38 UTC, lukaszewczak approved these changes

2019-06-05 18:45 UTC, matwjablonski approved these changes

2019-06-05 18:45 UTC, merged